export const styles = {
  "None": [""],
  Modern: [
    "clean lines",
    "minimalist design",
    "geometric shapes",
    "concrete patio",
    "gray tones",
    "modern outdoor furniture",
    "succulents",
    "low-maintenance plants",
    "fire pit",
    "simple lawn"
  ],
  Mediterranean: [
    "terra cotta tiles",
    "stone pathways",
    "olive trees",
    "lavender",
    "drought-tolerant plants",
    "fountains",
    "warm earth tones",
    "vine-covered pergolas",
    "wrought iron furniture",
    "gravel or crushed stone"
  ],
  Tropical: [
    "lush greenery",
    "palm trees",
    "bright flowers",
    "bamboo furniture",
    "water feature",
    "natural stone",
    "exotic plants",
    "tiki torches",
    "large leaves",
    "winding paths"
  ],
  "Japanese Zen": [
    "gravel or sand garden",
    "bamboo",
    "water feature",
    "moss-covered rocks",
    "stone lanterns",
    "bonsai trees",
    "minimalist plants",
    "wooden footbridge",
    "raked sand patterns",
    "shoji screen"
  ],
  "English Cottage": [
    "overgrown flower beds",
    "stone pathways",
    "wrought iron fencing",
    "roses",
    "lavender",
    "rustic wooden benches",
    "cobblestone patio",
    "wildflowers",
    "arbors covered in vines",
    "climbing plants"
  ],
  Desert: [
    "cacti",
    "succulents",
    "gravel and sand",
    "stone walkways",
    "drought-tolerant plants",
    "terra cotta planters",
    "boulders",
    "neutral tones",
    "dry riverbed",
    "minimalist landscaping"
  ],
  Rustic: [
    "wooden fences",
    "stone fire pit",
    "natural stone patio",
    "wild grasses",
    "wooden benches",
    "native plants",
    "stone walkways",
    "rustic outdoor lighting",
    "log seating",
    "natural water feature"
  ]
}

export const backyardFeatures = {
  "pool": { popularity: 86 },
  "outdoor kitchen": { popularity: 75 },
  "fire pit": { popularity: 80 },
  "garden": { popularity: 70 },
  "gazebo": { popularity: 65 },
  "deck": { popularity: 72 },
  "patio furniture": { popularity: 90 },
  "hot tub": { popularity: 68 },
  "fountain": { popularity: 55 },
  "grill": { popularity: 88 },
  "outdoor lighting": { popularity: 92 },
  "treehouse": { popularity: 40 },
  "shed": { popularity: 50 },
  "privacy fence": { popularity: 78 },
  "potted plants": { popularity: 85 },
  "arbor": { popularity: 47 },
  "lawn sculptures": { popularity: 32 },
  "waterfall": { popularity: 60 },
  "outdoor speakers": { popularity: 65 },
  "outdoor bar": { popularity: 74 },
  "swingset": { popularity: 58 },
  "hammock": { popularity: 66 },
  "greenhouse": { popularity: 52 },
  "stone pathway": { popularity: 69 },
  "bird bath": { popularity: 54 },
  "trampoline": { popularity: 45 },
  "raised garden beds": { popularity: 71 },
  "pergola": { popularity: 63 },
  "vegetable garden": { popularity: 67 },
  "fireplace": { popularity: 61 },
  "outdoor rug": { popularity: 48 },
  "outdoor heater": { popularity: 53 },
  "children's play area": { popularity: 55 },
  "basketball hoop": { popularity: 44 },
  "outdoor movie projector": { popularity: 38 },
  "outdoor art": { popularity: 30 },
  "gated entry": { popularity: 50 },
  "outdoor dining set": { popularity: 76 },
  "bird feeders": { popularity: 43 },
  "outdoor shower": { popularity: 49 },
  "rock garden": { popularity: 37 },
  "dog run": { popularity: 51 },
  "fence-mounted planter boxes": { popularity: 42 },
  "sand pit": { popularity: 28 },
  "outdoor sectional": { popularity: 55 },
  "outdoor clock": { popularity: 25 },
  "bench seating": { popularity: 60 },
  "climbing wall": { popularity: 22 },
  "outdoor pool table": { popularity: 27 },
  "solar lights": { popularity: 73 },
  "pond": { popularity: 41 },
  "butterfly garden": { popularity: 39 },
  "arbor swing": { popularity: 43 },
  "outdoor mirror": { popularity: 19 },
  "tiki torches": { popularity: 46 },
  "wicker furniture": { popularity: 57 },
  "outdoor storage box": { popularity: 64 },
  "outdoor fan": { popularity: 52 },
  "vertical garden": { popularity: 34 },
  "tree lights": { popularity: 62 },
  "stone fire pit": { popularity: 78 },
  "retractable awning": { popularity: 51 },
  "bamboo screening": { popularity: 40 },
  "outdoor pizza oven": { popularity: 49 },
  "wildflower meadow": { popularity: 31 },
  "garden gnomes": { popularity: 26 },
  "mosquito netting": { popularity: 58 },
  "wind chimes": { popularity: 45 },
  "rainwater collection barrels": { popularity: 38 },
  "outdoor workout area": { popularity: 33 },
  "container garden": { popularity: 56 },
  "privacy screens": { popularity: 66 },
  "rope lighting": { popularity: 61 },
  "outdoor chess set": { popularity: 25 },
  "solar garden decorations": { popularity: 53 },
  "barbecue island": { popularity: 59 },
  "tree bench": { popularity: 29 },
  "butterfly house": { popularity: 35 },
  "sundeck": { popularity: 60 },
  "orchard": { popularity: 47 },
  "herb garden": { popularity: 68 },
  "hanging plants": { popularity: 75 },
  "shaded seating area": { popularity: 77 },
  "carport": { popularity: 50 },
  "rock waterfall": { popularity: 57 },
  "solar water fountain": { popularity: 69 },
  "paver patio": { popularity: 71 },
  "outdoor herb planters": { popularity: 72 },
  "landscaped flower beds": { popularity: 74 },
  "outdoor storage shed": { popularity: 65 },
  "decorative mulch": { popularity: 67 },
  "cobblestone pathway": { popularity: 63 },
  "koi pond": { popularity: 54 },
  "drip irrigation system": { popularity: 49 },
  "raised deck": { popularity: 70 },
  "outdoor workbench": { popularity: 46 },
  "flagstone patio": { popularity: 48 },
  "butterfly friendly plants": { popularity: 46 },
  "metal sculptures": { popularity: 32 }
};